# Docker-Compose
# App: Visual Paradigm License Server
# Env: Production
vpserver:
    tty: true
    image: jrarseneau/vpserver
    restart: always
    hostname: vpserver
    domainname: vpserver.med.uolocal
    ports:
        - "1999:1999"
    volumes_from:
        - vpserver-data
    labels:
        io.rancher.sidekicks: vpserver-data
        io.rancher.scheduler.affinity:host_label: name=med-cdk-p01
    stdin_open: true

vpserver-data:
    tty: true
    image: jrarseneau/vpserver
    hostname: vpserver-data
    command:
        - cat
    volumes:
        - /opt/VPServer
    stdin_open: true
